### ISSUE TITLE
Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by miguelmota** [pdud/ember-cli-build-notifications#11]
I get the following when doing `ember s`

```bash
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:788:15)
    at Object.exports.exec (child_process.js:649:18)
    at Object.module.exports.command (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli-buil
d-notifications/node_modules/node-notifier/lib/utils.js:45:13)
    at NotificationCenter.notify (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli-build-no
tifications/node_modules/node-notifier/notifiers/notificationcenter.js:62:11)
    at Class.module.exports.buildError (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli-bu
ild-notifications/index.js:11:14)
    at /Users/moogs/Dropbox/Development/app/node_modules/ember-cli/lib/models/builder.js:122:34
    at Array.map (native)
    at Class.module.exports.Task.extend.processAddonBuildSteps (/Users/moogs/Dropbox/Development/app/n
ode_modules/ember-cli/lib/models/builder.js:120:43)
    at Class.<anonymous> (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli/lib/models/build
er.js:149:14)
    at lib$rsvp$$internal$$tryCatch (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli/node_
modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli
/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli/node_m
odules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$$internal$$publishRejection (/Users/moogs/Dropbox/Development/app/node_modules/ember-c
li/node_modules/rsvp/dist/rsvp.js:415:7)
    at lib$rsvp$asap$$flush (/Users/moogs/Dropbox/Development/app/node_modules/ember-cli/node_modules/
rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /bin/sh EMFILE
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by pdud** [comment]
Thanks for reporting!

I'd like to try help you out but I don't believe the error is in `ember-cli-build-notifications`.

The bottom of your trace includes `Error: spawn /bin/sh EMFILE`

The below seems like a relevant link w/ a solution.

https://github.com/sindresorhus/gulp-imagemin/issues/10
https://github.com/sindresorhus/gulp-imagemin/issues/10#issuecomment-35088803

Please feel free to re-open if this link doesn't help you out :)
